Debug: false
AppName:
AppSecret: ""
HttpServer:
  Port: ":18081"
  AllowCrossDomain: true # 是否允许跨域

Token:
  Sign: "ad-market"
  ExpiresAt: 259200

Sms:
  AccessKeyId: ""
  AccessKeySecret: ""
  TemplateCode: ""
  SignName: ""

Mysql:
  Host: ""
  Port: 3306
  Database: ""
  Prefix: ""
  Username: ""
  Password: ""
  Charset: "utf8mb4"
  SetMaxIdleConns: 10
  SetMaxOpenConns: 128
  SetConnMaxLifetime: 60
  ReadWrite: 0 # 1开启，0关闭
  SlowQuery: 2 # 慢 SQL

Redis:
  Host: "192.168.0.101:6379"
  Password:
  Db: 0
  KeyPrefix: "ad:market:"
  ExpireTime: 3600 # s

Logs:
  GinLogName: "/storage/logs/gin.log" # 设置 gin 框架的接口访问日志
  SysLogName: "/storage/logs/sys.log" # 运行时日志文件名，注意该名称不要与上一条重复 ,避免和 gin 框架的日志掺杂一起，造成混乱。
  TextFormat: "json" #记录日志的格式，参数选项：console、json ， console 表示一般的文本格式
  TimePrecision: "millisecond" #记录日志时，相关的时间精度，该参数选项：second  、 millisecond ， 分别表示 秒 和 毫秒 ,默认为毫秒级别
  MaxSize: 10 #每个日志的最大尺寸(以MB为单位）， 超过该值，系统将会自动进行切割
  MaxBackups: 7 #保留旧日志最大个数
  MaxAge: 15 #保留旧日志最大天数
  Compress: false #日志备份时，是否进行压缩

FileUploadSetting:
  Size: 100 # 单位 KB
  UploadPath: "/storage/app/upload"
  ReturnPath: "/web/storage/upload"

# https://mp.weixin.qq.com/wxamp/devprofile/get_profile?token=138641618&lang=zh_CN
WxLogin: # 参数在：开发 ->开发者管理 -> 开发设置中
  Url: "https://api.weixin.qq.com/sns/jscode2session"
  AccessToken: "https://api.weixin.qq.com/cgi-bin/token"
  UserMobile: "https://api.weixin.qq.com/wxa/business/getuserphonenumber"
  AppId: ""
  Secret: ""

WxPay:
  AppId: "wxaddafwedh2323aas"
  Mchid: "1200990042"
  SerialNo: "1200990042" # 微信商户 API 证书
  Amount: 100 # 订单金额￥1元整，单位（分）
  Desc: "天创跨境-体验课"
  NotifyUrl: "https://backend.skyki.com.cn/api/wxpay/action"
  ActionKey: ""
  H5:
    Order: "https://api.mch.weixin.qq.com/v3/pay/transactions/h5"

BDOCPC:
  EventUrl: "https://ocpc.baidu.com/ocpcapi/api/uploadConvertData"
  TOKEN: ""